language: cpp
dist: trusty
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libboost1.55-all-dev
    - libx11-dev
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - clang-format-3.7
    - clang-tidy-3.7
    - libstdc++-4.9-dev
os:
  - linux
  - osx
compiler:
 - clang
 - gcc
before_install:
 - cmake --version
 - $CC --version
 - $CXX --version
 - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ] ; then export CXX="g++-4.9" CC="gcc-4.9"; fi
 - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ] ; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make
