language: cpp
dist: xenial
os:
- linux
- osx
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libx11-dev
    - libbz2-dev
    - sshpass
    - libglu1-mesa-dev
    - g++-8
    - ninja
  homebrew:
    packages:
    - ninja
before_install:
- cmake --version
- $CC --version
- $CXX --version
script:
- pwd
- mkdir -p /home/travis/boost
- wget http://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
- tar --bzip2 -xf boost_1_60_0.tar.bz2
- cd boost_1_60_0/
- ./bootstrap.sh ${BOOST_BOOTSTRAP_FLAGS} --with-libraries=iostreams,filesystem,system --prefix=/home/travis/boost
- ./b2 link=static threading=multi runtime-link=shared cxxflags=-fPIC
- ./b2 install --prefix=/home/travis/boost
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- ls -l /home/travis/boost/include
- ls -l /home/travis/boost/lib
- cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/home/travis/boost -DBOOST_INCLUDEDIR=/home/travis/boost/include ..
- make
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L ../bin/datareftool/*.xpl ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ldd ../bin/datareftool/*.xpl ; fi
addons:
  artifacts:
    paths: bin/datareftool/*.xpl
    target_paths: /$(git rev-parse HEAD)/