language: cpp
os:
- linux
  dist: bionic
- osx
  osx_image: xcode10.2
addons:
  apt:
    packages:
    - cmake
    - libx11-dev
    - libbz2-dev
    - libglu1-mesa-dev
    - g++-8
  homebrew:
    packages:
    - ninja
  artifacts:
    debug: true
    s3_region: us-east-2
    paths:
    - mac.xpl
    - lin.xpl
    - win.xpl
    working_dir: ${TRAVIS_BUILD_DIR}/bin/datareftool/
    target_paths:
    - $(git rev-parse HEAD)
before_install:
- cmake --version
- $CC --version
- $CXX --version
install:
- export BOOST_DIR=~/boost
- wget -nv http://downloads.sourceforge.net/project/boost/boost/1.70.0/boost_1_70_0.tar.bz2
- tar --bzip2 -xf boost_1_70_0.tar.bz2
- cd boost_1_70_0/
- ./bootstrap.sh ${BOOST_BOOTSTRAP_FLAGS} --with-libraries=iostreams,filesystem,system --prefix=${BOOST_DIR}
- ./b2 link=static threading=multi runtime-link=shared cxxflags=-fPIC
- ./b2 install --prefix=${BOOST_DIR}
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
script:
- cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=${BOOST_DIR} -DBOOST_INCLUDEDIR=${BOOST_DIR}/include ..
- make
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L ../bin/datareftool/*.xpl ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd ../bin/datareftool/*.xpl ; fi
