language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
compiler:
 - clang
 - gcc
before_install:
 - ./.travis.before.install.$TRAVIS_OS_NAME.sh
 - cmake --version
 - $CC --version
 - $CXX --version
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make
