language: cpp
dist: trusty
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - cmake
    - libboost1.55-dev
    - libx11-dev
os:
  - linux
  - osx
compiler:
 - clang
 - gcc
before_install:
 - cmake --version
 - $CC --version
 - $CXX --version
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make
