language: cpp
dist: trusty
addons:
  apt:
    packages:
    - cmake
    - boost-latest
    - libx11-dev
os:
  - linux
  - osx
compiler:
 - clang
 - gcc
before_install:
 - cmake --version
 - $CC --version
 - $CXX --version
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make
