name: Compile

on: [push]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: vcpkg install libpng:x64-windows-static
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Prebuild
        run: mkdir -p build
      - name: CMake
        working-directory: build
        shell: cmd
        run: cmake -G "Visual Studio 17 2022" -DVCPKG_TARGET_TRIPLET=x64-windows-static -A x64 -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: MSBuild
        working-directory: build
        shell: cmd
        run: msbuild /p:Configuration=Release ALL_BUILD.vcxproj

      - uses: actions/upload-artifact@master
        with:
          name: drt_win_xp10
          path: build/src/plugin/Release/win.xpl
      - uses: actions/upload-artifact@master
        with:
          name: drt_win_xp11
          path: build/src/plugin/Release/datareftool.xpl
      - name: Dependencies
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dumpbin.exe /dependents build/src/plugin/Release/win.xpl
          dumpbin.exe /dependents build/src/plugin/Release/datareftool.xpl
